export const diseaseToDoctorMapping: Record<string, string> = {
  "Fungal Infection": "Dermatologist",
  "Acne": "Dermatologist",
  "Psoriasis": "Dermatologist",
  "Impetigo": "Dermatologist",
  "Allergy": "Allergist",
  "Drug Reaction": "Allergist",
  "GERD": "Gastroenterologist",
  "Peptic Ulcer Disease": "Gastroenterologist",
  "Gastroenteritis": "Gastroenterologist",
  "Chronic Cholestasis": "Gastroenterologist",
  "Hepatitis A": "Hepatologist",
  "Hepatitis B": "Hepatologist",
  "Hepatitis C": "Hepatologist",
  "Hepatitis D": "Hepatologist",
  "Hepatitis E": "Hepatologist",
  "Alcoholic Hepatitis": "Hepatologist",
  "Jaundice": "Hepatologist",
  "Migraine": "Neurologist",
  "Paralysis (brain hemorrhage)": "Neurologist",
  "Cervical Spondylosis": "Neurologist",
  "Vertigo": "Neurologist",
  "Heart Attack": "Cardiologist",
  "Hypertension": "Cardiologist",
  "Varicose Veins": "Cardiologist",
  "Diabetes": "Endocrinologist",
  "Hyperthyroidism": "Endocrinologist",
  "Hypothyroidism": "Endocrinologist",
  "Hypoglycemia": "Endocrinologist",
  "Arthritis": "Orthopedic",
  "Osteoarthritis": "Orthopedic",
  "Malaria": "General Physician",
  "Dengue": "General Physician",
  "Typhoid": "General Physician",
  "Common Cold": "General Physician",
  "Pneumonia": "Pulmonologist",
  "Bronchial Asthma": "Pulmonologist",
  "Tuberculosis": "Pulmonologist",
  "Chickenpox": "General Physician",
  "Dimorphic Hemmorhoids (piles)": "Proctologist",
  "Urinary Tract Infection": "Urologist",
  "AIDS": "Infectious Disease Specialist",
};

export function getDoctorType(disease: string): string {
  const trimmed = disease.trim();
  return diseaseToDoctorMapping[trimmed] || "General Physician";
}

export const specializations = [
  "General Physician",
  "Dermatologist",
  "Cardiologist",
  "Neurologist",
  "Orthopedic",
  "Gastroenterologist",
  "Endocrinologist",
  "Pulmonologist",
  "Hepatologist",
  "Allergist",
  "Urologist",
  "Proctologist",
  "Infectious Disease Specialist",
];
